### ISSUE TITLE
Demo/Showcasing

### ISSUE THREAD

**Issue by dereuromark** [lampager/lampager-cakephp#18]
Hi!
This looks like an interesting alternative to the default and simple paginators in core.

Are you interested in showcasing this in a new example demo page in the v4 version of the CakePHP Sandbox?
https://github.com/dereuromark/cakephp-sandbox (cake4 branch) => http://sandbox.dereuromark.de/

PS:
https://github.com/lampager/lampager-cakephp/blob/master/composer.json#L29
Sure this shouldnt be a require one? As you need the CakePHP core for this plugin to work.
At least the cakephp/orm 4.x one.

**Comment by chitoku-k** [comment]
Thank you for being interested in this project. We would love to have this in that demo page so let us know when it comes to happen!

BTW, I think I need to double check the require one. That part was absolutely inspired by cakephp/migrations though.

**Comment by dereuromark** [comment]
Migrations has sub Packages though 
https://github.com/cakephp/migrations/blob/1532530fd06d453668e7e32cf9fc3246d7f377cb/composer.json#L23
One of the two are necessary.

**Comment by chitoku-k** [comment]
Resolved in #19 and #20. Thanks about that!

**Comment by dereuromark** [comment]
Feel free to demo PR towards cake4 branch.
